version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample_backend
    ports:
      - 8930:8930
    expose:
      - "8930"
    networks:
      - sample_network
    healthcheck:
      test: curl -s -f http://backend:8930/health >/dev/null || exit 1
      interval: 30s
      timeout: 5s
      retries: 6

networks:
  sample_network:
